# Generated by Django 3.2.9 on 2021-12-06 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScheduleOrganizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseassignment',
            options={'ordering': ['complete', 'due_date']},
        ),
    ]
